chore: npm install warnings
sasjs/cli pull request #1038
Opened 2021-11-16 10:41 UTC by medjedovicm

## Intent
Resolved npm install warnings by updating `jest-cli` package.

2021-11-17 13:57 UTC, allanbowe commented on package.json
> +    "husky": "^7.0.4",
What is the licence for this?

2021-11-17 13:58 UTC, allanbowe requested changes
I don't believe the latest version of husky is free for commercial use (but correct me if I'm wrong)

2021-11-17 14:05 UTC, allanbowe commented on package.json
> +    "husky": "^7.0.4",
MIT (now) it seems

2021-11-17 14:05 UTC, allanbowe commented
I was wrong - they changed their licence in version 7:  https://github.com/typicode/husky/pull/916/files#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7

2021-11-17 14:05 UTC, allanbowe submitted a review, later dismissed

2021-11-30 01:27 UTC, saadjutt01 approved these changes

2021-12-06 08:34 UTC, VladislavParhomchik approved these changes

2021-12-06 12:07 UTC, merged