feat(test-command): add @sasjs/server support
sasjs/cli pull request #1118
Opened 2022-02-15 08:11 UTC by YuryShkoda

## Issue

Closes #1108 

## Intent

- Add `@sasjs/server` support to `sasjs test` command

## Implementation

- Added logic to support `SASJS` `ServerType`.
- Added unit test to cover the new functionality.

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
- [x] Any new functionality has been unit tested.
- [ ] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [ ] Reviewer is assigned.

2022-02-15 08:47 UTC, allanbowe commented on src/commands/testing/spec/testing.spec.server.ts
> +          : 'SASStoredProcess'
is this VIYA specific?  If so I guess it doesn't need SASStoredProcess.  If it's generic, it should probably include the Server API route as well?

2022-02-15 08:47 UTC, allanbowe commented on src/commands/testing/spec/testing.spec.server.ts
> +            '      Licensed to ANALYTIUM LTD- PARTNER LICENCE DATA MANAGER CLIENT, Site 70221619.\r\n' +
This part will break if we ever use a different platform

2022-02-15 08:47 UTC, allanbowe commented on src/commands/testing/spec/testing.spec.server.ts
> +            '      Licensed to ANALYTIUM LTD- PARTNER LICENCE DATA MANAGER CLIENT, Site 70221619.\r\n' +
The date will also be different whenever SAS restarts

2022-02-15 08:57 UTC, allanbowe commented on src/commands/testing/spec/testing.spec.server.ts
> +            '      Licensed to ANALYTIUM LTD- PARTNER LICENCE DATA MANAGER CLIENT, Site 70221619.\r\n' +
Ignore these comments - I did not realise this was a mocked response

2022-02-15 09:14 UTC, allanbowe approved these changes

2022-02-15 12:03 UTC, VladislavParhomchik submitted a review, later dismissed

2022-02-16 11:15 UTC, allanbowe requested changes
This is working fine (and SUPER fast!!), the only issue I see is that the console log path says `/SASStoredProcess` when it should say `/SASjsApi/stp/execute`.

This is just a display issue (also a functionality issue as you can't click it).  The test does indeed run.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/4420615/154253731-f10123ad-c1fb-4de2-8637-2a95aea64f56.png">

2022-02-16 12:05 UTC, allanbowe approved these changes

2022-02-16 12:19 UTC, merged