fix(compile): use @sasjs/core from cli if there is no such module in project folder
sasjs/cli pull request #1188
Opened 2022-04-11 14:16 UTC by YuryShkoda

## Issue

Closes #1113 

## Intent

- Use `@sasjs/core` from `@sasjs/cli/node_modules` if there is no such module in project folder.

## Implementation

- Add check if folder exists and use `@sasjs/cli/node_modules` as a fallback location for `sasjsConstants.macroCorePath`.
- Remomed redundant imports.
- Adjusted `setConstants.spec` to cover fallback scenario.

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
- [x] Any new functionality has been unit tested.
- [ ] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [x] Reviewer is assigned.

2022-04-11 15:03 UTC, sabhas approved these changes

2022-04-11 15:20 UTC, saadjutt01 submitted a review, later dismissed

2022-04-14 10:08 UTC, sabhas approved these changes

2022-04-14 10:39 UTC, allanbowe approved these changes

2022-04-14 10:40 UTC, merged

2022-04-14 10:45 UTC, saadjutt01 requested changes

2022-04-14 10:45 UTC, saadjutt01 commented on src/utils/utils.ts
> +    process.cwd(),
It needs to be the root of node application.

2022-04-14 10:45 UTC, saadjutt01 commented on src/utils/utils.ts
> +    cliDepsPath,
It's not necessary to be cli dependency. It may just be module name.