fix: should not authenticate against sasjs server running in desktop mode
sasjs/cli pull request #1226
Opened 2022-07-07 06:35 UTC by sabhas

## Issue

closes #1216

## Intent

* there's no need to authenticate against the target containing `serverType == SASjs` and the server is running in desktop mode.

## Implementation

* Added a utility function that calls the server's info api endpoint and checks if the server is running in server mode or not.

## Checks

- [ ] Code is formatted correctly (`npm run lint:fix`).
- [ ] Any new functionality has been unit tested.
- [ ] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [ ] Reviewer is assigned.

2022-07-07 10:50 UTC, medjedovicm commented on src/utils/utils.ts
> +    if (res.data.mode === 'server') return true
Could be written shorter like this:

```
return res.data.mode === 'server'
```

2022-07-07 11:29 UTC, medjedovicm approved these changes

2022-07-13 21:34 UTC, allanbowe commented
Before we merge this, given the additional dependency, it would be good to know two things:

1.  Will `npm i -g @sasjs/cli` continue to install without errors or warnings
2.  What is the impact on the bundle size, and hence the time to download the CLI?

2022-07-13 21:35 UTC, allanbowe requested changes
Before we merge this, given the additional dependency, it would be good to know two things:

1.Will npm i -g @sasjs/cli continue to install without errors or warnings
2. What is the impact on the bundle size, and hence the time to download the CLI?

2022-07-18 14:30 UTC, YuryShkoda commented on package.json
> +    "axios": "0.27.2",
You don't need to add `axios` as a dependency because it is already there (brought by `@sasjs/adapter`)

2022-07-18 14:31 UTC, YuryShkoda commented on src/utils/utils.ts
> +export const isServerRunningInServerMode = async (target: Target) => {
I would call it `isSasJsServerInServerMode`

2022-07-19 09:24 UTC, YuryShkoda commented on package-lock.json
> +    "node_modules/@sasjs/adapter/node_modules/axios": {
@sabhas , please roll back changes to `package-lock.json`

2022-07-19 09:46 UTC, sabhas commented
> 

we are no longer adding any additional dependency in this PR

2022-07-19 09:48 UTC, YuryShkoda approved these changes

2022-07-19 09:49 UTC, sabhas commented
> Before we merge this, given the additional dependency, it would be good to know two things:
> 
> 1.Will npm i -g @sasjs/cli continue to install without errors or warnings 2. What is the impact on the bundle size, and hence the time to download the CLI?


we are no longer adding any additional dependency in this PR

2022-07-19 09:54 UTC, allanbowe approved these changes

2022-07-19 09:54 UTC, merged