test(cb): compile, compilebuild and compile & build
sasjs/cli pull request #305
Opened 2020-12-04 23:24 UTC by saadjutt01

## Issue

Closes #303 

## Intent

What this PR intends to achieve.

## Implementation

What code changes have been made to achieve the intent.

## Checks

- [ ] Code is formatted correctly (`npm run lint:fix`).
- [ ] Any new functionality has been unit tested.
- [ ] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [ ] Reviewer is assigned.

2020-12-07 10:40 UTC, YuryShkoda requested changes

2020-12-07 10:40 UTC, YuryShkoda commented on test/commands/db.spec.js
> +import rimraf from 'rimraf'
use `deleteFolder` utility

2020-12-07 10:40 UTC, YuryShkoda commented on test/commands/job.spec.js
> +      appLoc: `/Public/app/cli-tests/${timestampAppLoc}`,
should be target name with timestamp

2020-12-07 12:02 UTC, saadjutt01 commented on test/commands/build.spec.js
> +      const parentFolderNameTimeStamped = `test-app-build-minimal${timestamp}`
All tests have `test-app-` as prefix, needs to be specific for deleting local folders for this test suite

2020-12-07 12:06 UTC, saadjutt01 commented on test/commands/add.spec.js
> +import rimraf from 'rimraf'
`rimraf` completely removed from tests

2020-12-07 12:07 UTC, saadjutt01 commented on test/commands/cb.spec.js
> +  describe('test-app-timestamp', () => {
removed unnecessary `describe` block

2020-12-07 22:23 UTC, allanbowe approved these changes

2020-12-08 06:09 UTC, YuryShkoda approved these changes

2020-12-08 07:43 UTC, merged