Issue 607
sasjs/cli pull request #632
Opened 2021-04-30 09:29 UTC by YuryShkoda

## Issue

closes #607 

## Intent

Implement `sasjs test` command

## Implementation

1. Updated 'compile' logic.
2. Implemented `sasjs test` command.

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
- [x] Any new functionality has been unit tested.
- [x] All unit tests are passing (`npm test`).
Mocked:
![image](https://user-images.githubusercontent.com/25773492/116676529-c0908600-a9af-11eb-9421-a00284da0efc.png)
- [ ] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [x] Reviewer is assigned.

2021-04-30 11:00 UTC, saadjutt01 requested changes

2021-04-30 11:51 UTC, YuryShkoda commented on package.json
> +    "ghooks": "^2.0.4",
good catch!

2021-04-30 14:57 UTC, krishna-acondy commented on src/commands/compile/internal/compileTestFile.ts
> +  console.log(
We should use the `process.logger` object to output this log.

2021-04-30 15:02 UTC, krishna-acondy commented on src/commands/compile/internal/compileTestFile.ts
> +  console.table(coverage)
On a related note, it'll be good to move that table-rendering functionality into the utils library, but we can do that as a separate piece of work.

2021-04-30 19:38 UTC, saadjutt01 submitted a review, later dismissed

2021-05-01 08:32 UTC, krishna-acondy approved these changes

2021-05-02 12:08 UTC, saadjutt01 approved these changes

2021-05-03 06:47 UTC, allanbowe approved these changes

2021-05-04 05:43 UTC, merged