fix(web): removed double encoding of CSS issue
sasjs/cli pull request #819
Opened 2021-07-03 10:01 UTC by saadjutt01

## Issue

Link any related issue(s) in this section.

## Intent

What this PR intends to achieve.

## Implementation

What code changes have been made to achieve the intent.

## Checks

- [ ] Code is formatted correctly (`npm run lint:fix`).
- [ ] Any new functionality has been unit tested.
- [ ] All unit tests are passing (`npm test`).
- [ ] All CI checks are green.
- [ ] JSDoc comments have been added or updated.
- [ ] Reviewer is assigned.

2021-07-04 19:17 UTC, allanbowe commented
windows tests passing
![image](https://user-images.githubusercontent.com/4420615/124396968-8f1c9980-dd15-11eb-99bb-c5085f2936fb.png)

2021-07-04 19:27 UTC, allanbowe requested changes
![image](https://user-images.githubusercontent.com/4420615/124397148-dc4d3b00-dd16-11eb-9f8a-c0109a650094.png)

The use of windows slashes in the generated SAS program is not valid for SAS logical folder paths

![image](https://user-images.githubusercontent.com/4420615/124397163-f1c26500-dd16-11eb-8471-cff52ba34f9a.png)


In the generated SAS program, we must always use forward slashes (`/`) to as a folder seperator
****

2021-07-04 23:44 UTC, saadjutt01 commented
> ![image](https://user-images.githubusercontent.com/4420615/124397148-dc4d3b00-dd16-11eb-9f8a-c0109a650094.png)
> 
> The use of windows slashes in the generated SAS program is not valid for SAS logical folder paths
> 
> ![image](https://user-images.githubusercontent.com/4420615/124397163-f1c26500-dd16-11eb-8471-cff52ba34f9a.png)
> 
> In the generated SAS program, we must always use forward slashes (`/`) to as a folder seperator

Fixed!
![image](https://user-images.githubusercontent.com/8914650/124402747-a4141f80-dd4b-11eb-9909-2dcc0a5cb41c.png)

2021-07-05 00:46 UTC, allanbowe commented
Feature is working now in SAS 9:
![image](https://user-images.githubusercontent.com/4420615/124404438-965a9c00-dd43-11eb-9534-ade142b0669e.png)

2021-07-05 06:39 UTC, krishna-acondy commented on src/commands/web/index.ts
> +  const nonBinaryFileTypes = ['html', 'CSS', 'JS']
Shouldn't `html` be uppercased as well?

2021-07-05 09:15 UTC, allanbowe commented on src/commands/web/index.ts
> +  const nonBinaryFileTypes = ['html', 'CSS', 'JS']
uppercased

2021-07-05 09:18 UTC, YuryShkoda commented on src/commands/build/build.ts
> +      : folderPath.replace(rootDirectory, '').split('\\').splice(1).join('/')
use `path.sep` to make it more robust

2021-07-05 09:34 UTC, allanbowe requested changes
Looks like the windows path update broke the non-windows build for Data Controller:
![image](https://user-images.githubusercontent.com/4420615/124450644-4ef8fd80-dd8d-11eb-9255-fb0700346f1a.png)

![image](https://user-images.githubusercontent.com/4420615/124450729-61733700-dd8d-11eb-88b1-45c71e641b38.png)

2021-07-05 09:34 UTC, saadjutt01 commented on src/commands/build/build.ts
> +      : folderPath.replace(rootDirectory, '').split('\\').splice(1).join('/')
done

2021-07-05 09:57 UTC, allanbowe requested changes
When building Data Controller, we are getting the following error in console:

![image](https://user-images.githubusercontent.com/4420615/124453974-992fae00-dd90-11eb-9137-f44cad6e6d19.png)

2021-07-05 12:26 UTC, saadjutt01 commented
> When building Data Controller, we are getting the following error in console:
> 
> ![image](https://user-images.githubusercontent.com/4420615/124453974-992fae00-dd90-11eb-9137-f44cad6e6d19.png)

Issue is resolved.

2021-07-05 20:52 UTC, allanbowe commented
Data Controller is building fine now

2021-07-06 06:15 UTC, krishna-acondy approved these changes

2021-07-06 07:18 UTC, allanbowe approved these changes

2021-07-06 07:18 UTC, merged