fix(web): added encoding to base64 *.js and *.css files for SAS9 targets
sasjs/cli pull request #95
Opened 2020-09-21 12:40 UTC by YuryShkoda

2020-09-21 12:53 UTC, krishna-acondy approved these changes

2020-09-21 14:49 UTC, allanbowe requested changes
Just one part left - when we _invoke_ `sasout()` we need to pass in JS64 or CSS64 instead of JS / CSS (SAS 9 only)

2020-09-22 07:10 UTC, YuryShkoda commented
> Just one part left - when we _invoke_ `sasout()` we need to pass in JS64 or CSS64 instead of JS / CSS (SAS 9 only)

fixed

2020-09-22 07:13 UTC, krishna-acondy submitted a review, later dismissed

2020-09-22 09:12 UTC, allanbowe approved these changes

2020-09-22 09:12 UTC, merged

2020-09-22 09:13 UTC, krishna-acondy commented
:tada: This PR is included in version 1.10.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@sasjs/cli/v/1.10.2)
- [GitHub release](https://github.com/sasjs/cli/releases/tag/v1.10.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: